### ISSUE TITLE
The gene is not in the right place

### ISSUE THREAD

**Issue by anxuan-web** [linzhi2013/MitoZ#110]
Hello,
I found that every gene in the result was in an inappropriate position. 

![aeb1093232d8f65064bb86bbaa0b8b3](https://user-images.githubusercontent.com/77531332/105185690-c8988880-5b6b-11eb-9732-2105ca3fc54d.png)

![98e6ad7b2ed9a6f08f6fd5445b403b5](https://user-images.githubusercontent.com/77531332/105185754-e4039380-5b6b-11eb-8783-3c403adef1b7.png)

I used 4 threads, so I think it's not because of multithreading.

**Comment by linzhi2013** [comment]
Hi anxuan-web ,

could you give more descriptions on this? Because for example, the first two genes (tRNAG, ND3) are in the right positions.

If what you meant is the 1-bp shift between the GenBank file and the summary.txt, yes, there's a but here (see https://github.com/linzhi2013/MitoZ/issues/87#issue-718609086)

**Comment by anxuan-web** [comment]
Hello，
For example，I downloaded th complete mitochondrial genome of the same species from NCBI. AS shown in the fagure, the starting gene is tRNAphe, so the other genes are in a different order.
![a9059902cdf976deeb4020ddca1636a](https://user-images.githubusercontent.com/77531332/105265679-fe6d5980-5bcb-11eb-93d9-a138f9972220.png)
I wonder if this difference is caused by different sofeware?  How to do it? Thanks!

**Comment by linzhi2013** [comment]
Please provide the GenBank Accession for your downloaded sequence.

Did you just "annotate" your downloaded sequence with MitoZ? Or if you "assembled" a NEW mitogenome from NGS data with MitoZ (even with the same dataset as the NCBI mitogenome).

 If you "annotate" the NEW mitogenome instead of the NCBI one, and surely the gene positions can be different from the NCBI one, because the "breakpoints" of two mitogenome can be different.

**Comment by linzhi2013** [comment]
https://user-images.githubusercontent.com/77531332/105185754-e4039380-5b6b-11eb-8783-3c403adef1b7.png

https://user-images.githubusercontent.com/77531332/105265679-fe6d5980-5bcb-11eb-93d9-a138f9972220.png

I can see that the relative gene orders in the two pictures are the same. So I think you assembled and annoated a NEW mitogenome.

**Comment by anxuan-web** [comment]
Hello，
I assembled and annoated a NEW mitogenome.
Downloaded sequence：Genbank No. JX014234

I think this link will solve my problem. Thank you very much!

**Comment by linzhi2013** [comment]
ok, that's great. Feel free to open new issues when necessary.
