### ISSUE TITLE
N in the assembly

### ISSUE THREAD

**Issue by wushyer** [linzhi2013/MitoZ#114]
Hi I found some N in the final assembly. Is there any possibility to add some polish tools to make it no gap.

Thanks
Shuangyang

**Comment by linzhi2013** [comment]
Don't forget to upload the email conversations in English. thanks!

**Comment by linzhi2013** [comment]
> https://github.com/linzhi2013/MitoZ
If there are sensitive data and you would like to send me emails so we can check it in more details, PLEASE ALSO raise a NEW issue FIRSTLY, and finally UPLOAD corresponding anwsers to this issue (both question and answer in English would be best), so that the same question won't be asked multiple times. You can use the "comment" function of Github issue page to post my answers to your created issue --- any one is able to "comment" an issue once it's been created. Otherwise, I would hesitate to reply to your email because I would probably have to answer the same questions over and over again later. Thanks!
