### ISSUE TITLE
BIo/SAeqIO. pm error when running annotation stage.

### ISSUE THREAD

**Issue by paul-bio** [linzhi2013/MitoZ#116]
Hi, I got an error. And I couldn't find solution...
Can you suggest any help?

Thanks.

Can't locate Bio/SeqIO.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /NFS/users/creo9447/software/MitoZ/release_MitoZ_v2.3/bin/visualize/draw_circos_for_mitogenome_auto_depth.pl line 5.
BEGIN failed--compilation aborted at /NFS/users/creo9447/software/MitoZ/release_MitoZ_v2.3/bin/visualize/draw_circos_for_mitogenome_auto_depth.pl line 5.
Error occured when running command:
perl /NFS/users/creo9447/software/MitoZ/release_MitoZ_v2.3/bin/visualize/draw_circos_for_mitogenome_auto_depth.pl --gb /NFS/users/creo9447/project/OVF-decapoda/1.Rimicaris_dairei-DECAPODA/2assembly-real/2.mitoz/3.annotate/tmp/1.rimicaris.annotation/1.rimicaris_mitoscaf.fa.gbf.sortedByLength --conf /NFS/users/creo9447/project/OVF-decapoda/1.Rimicaris_dairei-DECAPODA/2assembly-real/2.mitoz/3.annotate/tmp/1.rimicaris.annotation/visual_config.txt

**Comment by linzhi2013** [comment]
> Can't locate Bio/SeqIO.pm in @inc (@inc contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) 

This is possibly caused by either you were not in the MitoZ environment or your Perl-related environmental variables were not correct, since the above `@inc` variable does NOT contain any path related to a MitoZ environment.

Maybe you have modified the following variables previously:

```
PERL5LIB  # especially THIS ONE
PERL_LOCAL_LIB_ROOT
PERL_MB_OPT
PERL_MM_OPT
```
If you did, then when you `conda activate mitozEnv` (or `source activate mitozEnv`), the values of these variables still did not change, so it could not find the Perl module ` Bio/SeqIO.pm`.
