### ISSUE TITLE
depth interpretation

### ISSUE THREAD

**Issue by paul-bio** [linzhi2013/MitoZ#134]
![image](https://user-images.githubusercontent.com/73869977/132148570-9e697628-6a54-4ba6-9a5c-1f0e4a689194.png)

Hello, 
I analyzed my sample using MITOZ, and it seems very useful tool for me.

And I have a question regarding the depth.
As you can see from the picture, the purple ling indicates sequence depth.
Why is there a sudden depth changes? .. 

Can you give a hand? (by the way, all genes were annotated)

**Comment by Prunoideae** [comment]
Current *de novo* assemblers use *de Brujin* graph to resolve the read connections, and implement graph trimming/optimizing algorithms to speed up the assemble progress, in such a circumstance the optimized output may not firmly reflect to how the sequence originally was, and this is not resolvable since the process of 2nd gen sequencing will surely destroy the information.

It's better to check the reads mapping by tools like IGV, to see if here is really a gap which is opened because the assembler thinks it's opened, and also use other annotation tools like MITOS to check if the gapped region is or isn't a normal part of PCG. If such a region is considered as a gap in IGV, and annotation tools can't find a reference to this region, it's better to trim the region manually.

**Comment by linzhi2013** [comment]
> ![image](https://user-images.githubusercontent.com/73869977/132148570-9e697628-6a54-4ba6-9a5c-1f0e4a689194.png)
> 
> Hello,
> I analyzed my sample using MITOZ, and it seems very useful tool for me.
> 
> And I have a question regarding the depth.
> As you can see from the picture, the purple ling indicates sequence depth.
> Why is there a sudden depth changes? ..
> 
> Can you give a hand? (by the way, all genes were annotated)

Check your MT-genome around this region (you can get the approximate positions from the map). Probably the MT-genome has Ns for this region.

and if you want to get more detailed information, e.g. how many read pairs are there connecting the two ends of the Ns region, you indeed need to use tools like IGV.

**Comment by paul-bio** [comment]
Thanks Prunoideae and Linzhi.

I checked those regions and found it was consist with bunch of Ns....
And I am now on the mapping step as you mentioned.
and also I checked mtDNA annotation from MITOS1 and 2. And found the region which was annotated COX2 was divided into COX2-a and COX2-b.. 

If I found gap openning from IGV, should I trim one sequence followed by Ns? 
for example, 
5'  contigA----NNN----contigB 3'
I should trim the front region of contig B right?

**Comment by linzhi2013** [comment]
Hi Paul,

Firstly, you do not need to trim the sequence. 

Secondly, you can find COX2 genes of some closely related species, and perform a multiple sequence alignment together with the COX2 gene of your sample) on nucleotide or protein (better) level, so you can estimate the correct size of the gap.

This is because the number of Ns (gaps) in the assembly is not very accurate. 

In the end, you can use the tbl2asn to get a genbank file.

Thirdly, maybe MitoZ can handle the gap already and will not break the COX2 into two parts?
