### ISSUE TITLE
assembly is linear and atp 6 is missing

### ISSUE THREAD

**Issue by jhcaddisfly** [linzhi2013/MitoZ#142]
Hi,

I have a question. I used the following command to assemble the mitogenome:

udocker run --rm --volume=$PWD --workdir=$PWD guanliangmeng/mitoz:2.3 python3 /app/release_MitoZ_v2.3/MitoZ.py all2 --genetic_code 5 --clade Arthropoda --outprefix Ple  --thread_number 60 --fastq1 ./PO2_NKD180900774_HFFTMDMXX_L1_1_sub.fq --fastq2 ./PO2_NKD180900774_HFFTMDMXX_L1_2_sub.fq --fastq_read_length 150 --run_mode 2 --filter_taxa_method 1 --requiring_taxa 'Arthropoda'

The data is 1.8 G forward and 1.8G reverse Illumina reads (150 bp)

cat summary.txt gives:
#Seq_id        Length(bp)     Circularity    Closely_related_species
scaffold169    15556          no             Aleurodicus dispersus
---
Potential missing genes:
#Gene             total_missing_number
--------------------------------------
ATP8                                 1
tRNA-Glu                             1
tRNA-Ser                             2

cat errorsummary.val gives:
1 INFO:    SEQ_DESCR.OrganismIsUndefinedSpecies
NOTE: valid [SEQ_DESCR.OrganismIsUndefinedSpecies] Organism 'Test sp.' is undefined species and does not have a specific identifier. DESCRIPTOR: BioSrc: Test sp. BIOSEQ-SET: lcl|scaffold169

cat Plectrocnemia_conspersa_mitoscaf.fa.val gives:
NOTE: valid [SEQ_DESCR.OrganismIsUndefinedSpecies] Organism 'Test sp.' is undefined species and does not have a specific identifier. DESCRIPTOR: BioSrc: Test sp. BIOSEQ-SET: lcl|scaffold169

My questions:
1.Aleurodicus dispersus (Hemiptera) is a closely related species but my species is of a different insect order. Why?
2.Why is my assembly not circular? What can I do to get it circular?
3. How can I get the missing genes?
4. Can you please explain what the purple and blue bars mean in the circos.png plot?

I ran a second round of udocker:
udocker run --rm --volume=$PWD --workdir=$PWD guanliangmeng/mitoz:2.3 python3 /app/release_MitoZ_v2.3/MitoZ.py all2 --genetic_code 5 --clade Arthropoda --outprefix 2ndround --thread_number 60 --fastq1 clean.1.fq.gz --fastq2 clean.2.fq.gz --fastq_read_length 150 --insert_size 250 --run_mode 3 --filter_taxa_method 1 --requiring_taxa 'Arthropoda' --quick_mode_seq_file work71.mitogenome.fasta --quick_mode_fa_genes_file quick_mode_fa_genes.txt --missing_PCGs ATP8 --quick_mode_score_file work71.hmmtblout.besthit.sim.filtered.high_abundance_10.0X.reformat.sorted --quick_mode_prior_seq_file work71.hmmtblout.besthit.sim.filtered.fa

This run did not finish but I ended up with a file called work91.mitogenome.fa which was just a little bit longer and circular.

Thank you,
J.

**Comment by linzhi2013** [comment]
Hi J.,

Sorry for my late reply.

> 1.Aleurodicus dispersus (Hemiptera) is a closely related species but my species is of a different insect order. Why?

It depends on what kinds of species are in MitoZ's mitochondrial genome database. Could be due to your order is lack in MitoZ's database.

> 2.Why is my assembly not circular? What can I do to get it circular?

Simply because the assembled mitochondrial genome is not long enough, and MitoZ cannot find the overlapping regions at the 5' end and 3' end of the assembled mitochondrial genome.

You can try to use a different kmer (default is 71) and could possibly get a circular genome, since yours is already quite long.

I didn't know why "This run did not finish but I ended up with a file called work91.mitogenome.fa which was just a little bit longer and circular." But you can `annotate`  this `work91.mitogenome.fa ` file directly with MitoZ, and check what genes are missing.

> 3. How can I get the missing genes?

Use the `work91.mitogenome.fa ` file .

> 4. Can you please explain what the purple and blue bars mean in the circos.png plot?

Please refer to https://github.com/linzhi2013/MitoZ/issues/11 , https://github.com/linzhi2013/MitoZ/issues/33 or https://github.com/linzhi2013/MitoZ/issues/123.

**Comment by jhcaddisfly** [comment]
Thank you for your quick answer!!!!
How can I look at the sequence content of this region? My data looks like this for all my mitogenomes.

All the best,
Jacqueline
