### ISSUE TITLE
Other animal taxa?

### ISSUE THREAD

**Issue by Tesserazoa** [linzhi2013/MitoZ#164]
## MitoZ version?
3.4

## How did you install MitoZ? (e.g. Docker, Udocker, Singularity, Conda-Pack, Conda, or source code) 
Conda

## Did you run a test after your installation, and was the test run okay? 
yes

## The command you used? 
--required_taxa Cnidaria

## Problem description 
Are other animal taxa incorporated, or are the only choices: "Chordata,Arthropoda,Echinodermata,Annelida-segmented-worms,Bryozoa,Mollusca,Nematoda,Nemertea-ribbon-worms,Porifera-sponges"? Of course there are many other animal phyla that are of interest.

Thanks!

**Comment by linzhi2013** [comment]
Hi Tesserazoa,

When your target species is not in the available clades, you can still use MitoZ. 

You can choose one of the clades used for mitochondrial sequence searching (the `-clade` option), and at the same time, specify a loose `-requiring_taxa` so that it would cover your target species (say Metazoa) (and thus your target species won't be filtered out, but MitoZ should still work if the mitogenome is long with >= 5 PCGs even you choose a different rank not containing your target species).

And set a proper genetic code table for your species.

In case the existing database doesn't work well for the gene annotation, you can check out https://github.com/linzhi2013/MitoZ/wiki/Extending-MitoZ%27s-database

**Comment by Tesserazoa** [comment]
Thank you for the prompt and helpful reply. Will give that a try, and consider adding new references.

**Comment by linzhi2013** [comment]
See https://github.com/linzhi2013/MitoZ/wiki/FAQ#can-i-apply-mitoz-to-other-clades
