### ISSUE TITLE
Missing genes with Udocker

### ISSUE THREAD

**Issue by parmardrashti** [linzhi2013/MitoZ#171]
## Problem description

# Log messages from MitoZ (stdout and stderr)

**Comment by parmardrashti** [comment]
Hi,
I have been running MItoZ v 3.3, installed through Udocker, megahit and multiple k-mers (tried with changing k-mers,too)
My results shows missing genes although "out.megahit.hmmtblout.besthit.sim.filtered-by-taxa.high_abundance_10.0X" file shows the those genes. Also, the .fasta file for the high abundance is not generated so I can not annotate it further.
I have tried changing the header of the final mitogenome fasta file and re-annotated. It worked in most cases but still, it fails to give the genes with complete length. 
I am attaching one of the "summery file" and "out.megahit.hmmtblout.besthit.sim.filtered-by-taxa.high_abundance_10.0X" file
[summary.txt](https://github.com/linzhi2013/MitoZ/files/10014083/summary.txt).
[out.megahit.hmmtblout.besthit.sim.filtered-by-taxa.high_abundance_10.zip](https://github.com/linzhi2013/MitoZ/files/10014089/out.megahit.hmmtblout.besthit.sim.filtered-by-taxa.high_abundance_10.zip)

I would really appreciate your help.
Thank you!

P.S. i have also tried to get the complete length of genes through introducing breakpoint. But, since there are multiple contigs in final fasta file, it does not give the desired result. Could you please help in this case also?

**Comment by linzhi2013** [comment]
Hi [parmardrashti](https://github.com/parmardrashti),

Based on your resulting files, your mitogenome is too fragmented, which probably is the reason that you didn't get genes with complete length.

```
#Seq_id        Length(bp)     Circularity    Closely_related_species
k99_227995     445            no             Hemilucilia
k99_167409     2680           no             Phormia regina
k99_26651      2598           no             Calliphora vomitoria
k99_142361     1813           no             Chrysomya putoria
```

To be sure, you can try the test dataset with your Udocker verion of MitoZ. If the assembly is a single sequences with all genes found, it indiciates that your problem is not related to Udocker.

If Udocker doens't work for you, you can also try the [Conda pack](https://github.com/linzhi2013/MitoZ/wiki/Installation#4-conda-pack) version.

And you can also try different assemblers and kmers in MitoZ to see if you can get a better mitogenome.


Cheers
Guanliang

**Comment by parmardrashti** [comment]
Thank you Guanliang for prompt reply.
As a matter of fact, I have been running other samples too. And majority has worked through Udocker. So, as you said it might be specific samples which has fragmented mitogenome.
I have tried these samples with mitoassemble but it ran for one and half weeks after which I had to manually stop it as it was going nowhere. But may be spades can help in this situation. I will try that too.
Thank you !!!

**Comment by linzhi2013** [comment]
Hi @parmardrashti ,

You are wellcome!

You can try smaller kmers, e.g. `--kmers_megahit 31 41 51 61 71 81 `, since smaller kmers will increase the abundance of some kmers in the DBG, which might be helpful sometimes.

All the best
Guanliang
