### ISSUE TITLE
Megahit sync PE fastq

### ISSUE THREAD

**Issue by Phismil** [linzhi2013/MitoZ#195]
Dear Guanliang 
Thank you for maintaining the repository.
I have a question regarding Megahit option in MitoZ.
Do paired-end reads needs to be sync before assembly?
Thank you in advance

**Comment by linzhi2013** [comment]
Hi @Phismil ,

Do you mean that fq 1 and fq2 IDs have to match each other? Yes, otherwise, the assemblers will complain. (and you get the wrong pair-end information, which is used to construct scaffolds)

Sometimes, the fq1 and fq2 are not in the same order, for example, one read record is lost in fq2 for unknown reasons.

I saw a program to filter out paired reads, but can't remember it now.

**Comment by linzhi2013** [comment]
You can also treat your data as single-end reads by using only the `-fq1` option but not `-fq2` option:
(1) use only your fq1 file;
(2) concatenate your fq1 and fq2 files into a single file.

**Comment by Phismil** [comment]
Thank you for your advice.  BBMap has a tool to sync PE files.
Cheers

**Comment by linzhi2013** [comment]
I just found the one I have mentioned: https://github.com/linsalrob/fastq-pair
