### ISSUE TITLE
你好，我在使用mitoz时遇到了一些问题。我正在使用的脚本是“mitoz all -- outfix text -- fq1 text -- fq2 text -- data_size_for_mt_assembly 3,0-- assembler megahit -- requiring _taxa”。同一脚本有两对样本，一组成功运行了结果，另一对报告了错误。显示的代码是运行创世纪外壳文件运行基因将结果转换为gff3格式Cat：'/ Csd5057. megait. hmmtblout. besthit. sim. fa. genewise/*/*. genewise ': 不存在那个文件或目录 抱歉，注释没有结果！请问原因是什么

### ISSUE THREAD

**Issue by sjhku** [linzhi2013/MitoZ#199]

**Comment by linzhi2013** [comment]
Hi,

Please check the content of these files:

```
-rw-rw-r-- 1 gmeng gmeng 5.5K Jun 29 05:40 DM01.megahit.hmmtblout.besthit
-rw-rw-r-- 1 gmeng gmeng 1.8K Jun 29 05:40 DM01.megahit.hmmtblout.besthit.sim
-rw-rw-r-- 1 gmeng gmeng 272K Jun 29 05:40 DM01.megahit.hmmtblout.besthit.sim.fa
-rw-rw-r-- 1 gmeng gmeng  23K Jun 29 05:43 DM01.megahit.hmmtblout.besthit.sim.filtered-by-taxa.fa

```

Your mentioned problem can happen if MitoZ failed to assemble mitogenomes.

Please provide more details if you still can't figure it out.


Best

**Comment by sjhku** [comment]
Hi

I have reviewed the four files mentioned above,but only the first file has over 300 bytes,and the other files are empty.Could you tell me the reason?

Thanks for your answer.

**Comment by linzhi2013** [comment]
It is simply because MitoZ failed to assemble mitogenomes from your input fastq files. This can happen for many reasons. But you can try to (1) use more data; (2) smaller kmers; and (3) other assemblers; (4) change your input data, for example, your fastq file could have very low proportion of mt-reads. 

I cannot give you more specific answers since you provided very little information.
