### ISSUE TITLE
NCBI installation updates

### ISSUE THREAD

**Issue by ekarsalan** [linzhi2013/MitoZ#2]
Dear MitoZ team,
Thanks for updating and maintaining the repository.
I have a question regarding installing NCBI database  inside ete3 package command:

from ete3 import NCBITaxa
ncbi = NCBITaxa()
ncbi.update_taxonomy_database()

Many HPC actually refuse to give FTP right  to the users.However the NCBI database are all already installed  locally.
I went through the source codes and it seems mitoz actually need FTP connection for creating populating database when first executed. I see we can change the database later  on but i don't see how we can feed a local NCBI database to the function "ncbi = NCBITaxa()".
I am wondering if you have any suggestions regarding solving the issue.
Thanks in advance

**Comment by linzhi2013** [comment]
Dear aremkho,

This is a very good question.

I noticed this problem during the development of MitoZ. MitoZ relies on the ETE3  pakcage, which must install the NCBI taxonomy database into `~/.etetoolkit/` directory:
    
    .etetoolkit/
    ├── taxa.sqlite
    └── taxa.sqlite.traverse.pkl

As you can see, the ETE3 package will transform the `ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz` into two files: `taxa.sqlite` and `taxa.sqlite.traverse.pkl` under the  `~/.etetoolkit/` directory. So the taxonomy database on your HPC
will not work for ETE3 package.

My goal was to install the database into somewhere else,  then I checked the ETE3's source code, and found that I cannot do it easily, because one has to modify much of the ETE3's source code.

Since I want to make it more easily to distribute MiotZ, for example, use `conda` to install all relevant dependencies automatically, so I gave up on this.

NB: I am currently updating MitoZ, but the version 2.2 is still testing: the algorithm is the same as verion 1.0, changes only  invoked to make it more user-friendly.

Cheers,
Guanliang Meng

**Comment by linzhi2013** [comment]
Dear Arsalan,

Thank you very much!

Now I'm going to close the issue. Please open new issues if you have questions.

**Comment by linzhi2013** [comment]
Closed since the limitation is from ETE3 package.
