### ISSUE TITLE
report in file "*.errorsummary.val"

### ISSUE THREAD

**Issue by LIFanAr** [linzhi2013/MitoZ#29]
Dear Guanliang,

Thank you providing us such a powerful tool! I will recommend it to everyone who needs.

BTW, given that the procedure have generated a circled mitochondrial genome for my species, I am not very clear why those errors occurred in *.errorsummary.val file, could you give more explanation on each hint as below?
#####
     5 ERROR:   SEQ_FEAT.NoStop
     1 WARNING: SEQ_INST.CompleteCircleProblem
     1 INFO:    SEQ_DESCR.OrganismIsUndefinedSpecies
#####

Thank you very much!

Fan

**Comment by linzhi2013** [comment]
Hi Fan,

1. The NCBI's program tbl2asn will give you the "SEQ_FEAT.NoStop" errors when it cannot find the standard stop codons (e.g. TAA). But it is true for some PCGs of some species that TAA stop codon is completed by adding 3′ A residues to the mRNA.

So you can compare the result PCG with such problem with the PCGs of some closely-related species to confirm if the result from MitoZ is normal (e.g. PCG length, similarity)

2. "SEQ_INST.CompleteCircleProblem": could be caused by the informal attribute information in the *.fsa file. The tbl2asn asks for `[key=value]` format, e.g. `[topology=linear]`

3. "OrganismIsUndefinedSpecies":  You do not need to care about this.  Now to submit mitogenome to Genbank, you just need two files: *.fsa and *.tbl. In the *.fsa file, you can set an attribute: `[organism=species name]`. then NCBI will automatically find the lineage of this species from their Taxonomy database. If not found, it will give you guidelines.


Cheers,
Guanliang

**Comment by LIFanAr** [comment]
Excellent! Very clear!

You saved my day.

THANK YOU!

Fan
