### ISSUE TITLE
About the depth distribution question

### ISSUE THREAD

**Issue by zhounan1356** [linzhi2013/MitoZ#33]
Dear professor Meng
       In this sentence "if the depth larger than upper quartile, it turns dark green as same with the outline"  I find that there is no dark green as the same with the outline in my output images. Is this my script mistake or input fastq data is wrong? My script:
python3 MitoZ.py visualize \
--circos circos \
--gb zzz.gb \
--gc yes \
--win 50 \
--gc_fill 128,177,211 \
--run_map yes \
--bwa bwa \
--thread 2 \
--depth_fill 190,186,218 \
--fq1 clean.1.fq.gz \
![image](https://user-images.githubusercontent.com/48699736/69789165-f8affa00-11fa-11ea-964a-69c0c42d2dff.png)
 Thanks for your attention to this question!

**Comment by linzhi2013** [comment]
Dear Zhounan,

The image seems good. Maybe @comery  can help with your question?

**Comment by comery** [comment]
HI, zhounan (hope I am right),

In the above example, you have defined "--depth_fill" by 190,186,218, which means it would fill depth region by 190,186,218 (a kind of light purple). However, the original sentence "if the depth larger than upper quartile, it turns dark green as same as the outline" that assumed under default color (dark green). So sorry for my expression make you confused.

My suggestion is that you can ignore that sentence, just set color as you wish.

**Comment by zhounan1356** [comment]
Dear professors
     Appreciate both of your help, more detail my confusion was that compared my result with the picture from  "MitoZ: a toolkit for animal mitochondrial genome assembly, annotation and visualization", are different. 
![image](https://user-images.githubusercontent.com/48699736/69810690-6c67fc00-1227-11ea-81ad-36e0f52ec6c2.png)
The middle circle, "if the depth larger than upper quartile, it turns dark green as same as the outline", is that means there are no depth lager than the upper quartile in my data, or my script is wrong? Many thanks

**Comment by comery** [comment]
Dear Zhounan,

I think your image looks great. The only reason why they are different, in my view, is color settings in scripts. So I checked the script (```release_MitoZ_v2.4-alpha/bin/visualize/draw_circos_for_mitogenome_auto_depth.pl```) in the visualize module. I found it could be a mistake in L666 and L667. It should be set as the default value - "dgreen". Now you can modify it by yourself, and I will update this script. by the way, it could happen that no depth is larger than the upper quartile because that the upper quartile is just 3/4 top of the whole dataset.
![image](https://user-images.githubusercontent.com/8231694/69823745-c75c1c00-1244-11ea-9d33-6d9cb0e5b9e7.png)

Thank you for reporting this bug!


best wishes,
Chentao

**Comment by zhounan1356** [comment]
Dear comery 
After your help, the problem has been solved. Thank you very much. Have a good day today!
Many thanks 
Zhounan
