### ISSUE TITLE
Could not open blosum62.bla as a filename for read Blast matrix

### ISSUE THREAD

**Issue by zskysafe** [linzhi2013/MitoZ#42]
I'm sorry to disturb you so many times, but I still have some questions to ask you.

Warning Error
	Could not open blosum62.bla as a filename for read Blast matrix
Warning Error
	Could not read Comparison matrix file in blosum62.bla
Fatal Error
	Could not build objects!

[mitoz.log](https://github.com/linzhi2013/MitoZ/files/4079904/mitoz.log)

python3  $DIR_mitoz/MitoZ.py all --genetic_code 5 --clade Arthropoda --outprefix $abb \
--thread_number 8 \
--fastq1 $fq1 \
--fastq2 $fq2 \
--fastq_read_length 150 \
--insert_size 250  \
--run_mode 2 \
--filter_taxa_method 1 \
--requiring_taxa 'Arthropoda' >> mitoz.log 2>&1

[findmitoscaf.log](https://github.com/linzhi2013/MitoZ/files/4079907/findmitoscaf.log)
python3 $DIR_mitoz/MitoZ.py findmitoscaf --genetic_code 5 --clade Arthropoda --outprefix $abb \
--thread_number 8 \
--from_soaptrans \
--fastafile $scafSeq >> findmitoscaf.log 2>&1

I have this problem running both ways, but I didn't find the file(blosum62.bla).

**Comment by linzhi2013** [comment]
Hi zskysafe,

It does not matter.

anyone who can meet this problem `Could not read Comparison matrix file in blosum62.bla` ,  is because your system recognize lowercase and uppercase files with the same name are the same, and then the system only keeps one of them.

The source codes actually provides both `BLOSUM62.bla` and `blosum62.bla` (picture below), but I can assert that in your current source directory (`release_MitoZ_v2.4-alpha/bin/annotate/wisecfg`), you can only find `BLOSUM62.bla`.
![image](https://user-images.githubusercontent.com/6203542/72657844-8f6f8a80-39e4-11ea-94db-335f77e10160.png)

As far as I know, Mac OS is such a system.
![image](https://user-images.githubusercontent.com/6203542/72657893-2a686480-39e5-11ea-84e4-3781b59441b0.png)

Thus, if the source code has been temporarily stored in a Mac OS, only the `BLOSUM62.bla`  file will be kept and the `blosum62.bla` file will be discarded. Next time, you upload this source code to another Linux machine, you can only see the `BLOSUM62.bla`  file .

Cheers
