### ISSUE TITLE
The topology of sequence ID 

### ISSUE THREAD

**Issue by orient100** [linzhi2013/MitoZ#5]
In you mannual about rearrangement  the mitochondrial genome sequence, i want to know if the sequence ID is reference mitogeome from NCBI.

**Comment by linzhi2013** [comment]
> In you mannual about rearrangement the mitochondrial genome sequence, i want to know if the sequence ID is reference mitogeome from NCBI.

Hi orient100,

the sequence id is only the id of your input sequence (i.e., `--fastafile`). When you use MitoZ to `annotate` a mitogenome, you must provide your sequence with the `--fastafile` option. 

The topology of your sequence should be declared on the sequence id line, for example, `>seq1 topology=circular`.

Because as far as we know, a complete mitogenome is circular in nature. Thus, if you get a complete mitogenome, you should claim that your sequence (`--fastafile`) is `topology=circular`. Otherwise, `topology=linear` should be used. This usage is the same as the Genbank format file in the NCBI.


Cheers

**Comment by linzhi2013** [comment]
please free to open new issues.
