### ISSUE TITLE
How to optimize the assembly result and ensure accuracy

### ISSUE THREAD

**Issue by depengl** [linzhi2013/MitoZ#50]
Hello Guanliang

I tried to assemble a mito-genome from WGS data,but the result is two linear sequences. I have several questions:
1.Whether extracting more data would be better for assemble(such as 8Gb with parameter --fq_size 8)? 
2.The missing data is control region ,not  PCGs, so are all parameters are required when rerun --run_mode3(such as "missi ng_PCGs =")?  
3. Can I apply closely-related species' mito-genome sequence in MitoZ?
4. How can I run all2 mode without extraction function when rerunning run_mode3?

Thank you!
Depeng

**Comment by linzhi2013** [comment]
> 1.Whether extracting more data would be better for assemble(such as 8Gb with parameter --fq_size 8)?

Hi Depeng,

Glad to know that you have solved several questions!

1. yes, sometimes the result mitogenome is fragmented is due to not enough data. To be specific, it is due to there is not enough mito-reads in the dataset. When this is the case, providing more data may get complete assembly.

2. if the above method does not work for you, and you can try to use ` --run_mode 3`, and randomly give some `missing_PCGs`.

3. MitoZ does not rely on reference (e.g. closely related species' mitogenome).

4. I do not get your point for this.

Cheers,
Guanliang

**Comment by depengl** [comment]
Thank you for your reply! I am rerunning the job. Hope to get a good assembly!

**Comment by matthewholding28** [comment]
Hello, 

I just want to echo the point #4 for this issue. When running in all2 mode, and providing clean files, the program is still starting by downsampling reads to create the .partial.fq.gz files. 

I am also have the same issue they did, where the control region is failing to completely assemble, and so my sequence is not completely circular. Interestingly, I have a large pile of coverage depth at the end of the control region/d-loop, but do not know how to interpret this: 


![Brid circos](https://user-images.githubusercontent.com/32144511/83060140-ff43f080-a028-11ea-81df-6e8ea124ea21.png)


Matt

**Comment by Prunoideae** [comment]
Hello matthewholding28,

> the program is still starting by downsampling reads to create the .partial.fq.gz files.

Sampling is always, since mitochondrial genome is of ultra high depth in raw reads, it's neither necessary nor efficient to use the whole sample as one read, so extracting only a partial of them will be just enough. You can tell the toolkit to extract a larger dataset if you are feeling that something is missing.

> where the control region is failing to completely assemble, and so my sequence is not completely circular

There will always be such a problem if your dataset is of not enough information, like too small dataset size (after filtering), or too low data quality.

> a large pile of coverage depth at the end of the control region/d-loop

Such graph indicates that this region have much more reads aligned to it than other regions from `bwa`, if you use `samtools` and `IGV` to visualize the result, you may find such a region has many reads, but with a great possibility having many indels or mismatchings.

This is hard to precisely classify what the cause is, but there are some possible cause of this:

1. Contamination, or nucleic sequences are considered in such assembly, or just this region is too hard to be precisely cloned by the bridge PCR.
2. This region of mitochondrial genome is of high variety itself, mitochondrion process a high copy in cells, variety is also then amplified.

Cheers

**Comment by linzhi2013** [comment]
> I am also have the same issue they did, where the control region is failing to completely assemble, and so my sequence is not completely circular. Interestingly, I have a large pile of coverage depth at the end of the control region/d-loop, but do not know how to interpret this:

Hi Matt,

1. control region 

In many species, the control regions are AT-rich and have repeats. All kmer-based assemblers have technical difficulties in assembling such regions.  the main reason for this is the  read length (and/or kmer length) is too short. For example, if the length of repeat unit is 400 bp, but typical NGS reads have only read length 100-150 bp, algorithms cannot determine where a read should be placed during alignment. And in the DBG graph during assembly, different repeats form only a single "circle", we cannot determine how many copies of repeats exist.

2. downsampling problem.

The MitoZ-2.4-alpha will do downsampling. this is because some users always provide all data they have and lead to MitoZ take a very long time to run. But I should enhance this aspect and users can choose downsampling or not.


Best
