### ISSUE TITLE
The issue about had not find visualization/circos.png 

### ISSUE THREAD

**Issue by orient100** [linzhi2013/MitoZ#6]
Hi,
I noticed some result is not good by using Mitoz to assemble and annotate mtDNA sequence, i do not known if it is the sample or others reason.The details are as follows: it will report an error  cannot stat 'visualization/circos.png, have not circos.png in ZZZ.result  and the result of assembly is very fragile.

**Comment by ColtrainJohn** [comment]
Hi. I have the same problem on the visualization step. Are there any suggestions how to solve the issue?


 at /home/work/miniconda3/envs/mitozEnv/bin/../lib/Circos/Error.pm line 425.
        Circos::Error::fatal_error("track", "max_number", 123504, "line", "/media/work/data/SS/Mitoz/Leech_mito1/Leech_margoi.step2/tmp/"..., 25000) called at /home/work/miniconda3/envs/mitozEnv/bin/../lib/Circos.pm line 1562
        Circos::run("Circos", "_cwd", "/media/work/data/SS/Mitoz/Leech_mito1/Leech_margoi.step2/tmp/"..., "configfile", "/media/work/data/SS/Mitoz/Leech_mito1/Leech_margoi.step2/tmp/"..., "_argv", "-conf /media/work/data/SS/Mitoz/Leech_mito1/Leech_margoi.step"...) called at /home/work/miniconda3/envs/mitozEnv/bin/circos line 536
cp: cannot stat ‘visualization/circos.png’: No such file or directory
Error occured when running command:
cp test_mitoscaf.fa.gbf test_mitoscaf.fa.sqn test_mitoscaf.fa.val errorsummary.val visualization/circos.svg visualization/circos.png  /media/work/data/SS/Mitoz/Leech_mito1/Leech_margoi.step2/test.result

**Comment by linzhi2013** [comment]
Hello,

You can go the `/media/work/data/SS/Mitoz/Leech_mito1/Leech_margoi.step2/tmp/` and find the result files `test_mitoscaf.fa.gbf test_mitoscaf.fa.sqn test_mitoscaf.fa.val errorsummary.val visualization/circos.svg`. Because at this final step, MitoZ only copy these files to ` /media/work/data/SS/Mitoz/Leech_mito1/Leech_margoi.step2/test.result`.

Or if you want, you can modify the MitoZ.py script, so that MitoZ doesn't copy the absent files anymore.

Cheers
