### ISSUE TITLE
MitoZ pulling from Shub failed

### ISSUE THREAD

**Issue by siuiylee** [linzhi2013/MitoZ#7]
![error](https://user-images.githubusercontent.com/49437001/55791873-04c33c00-5af2-11e9-8ba4-73e40232a2cf.jpg)

I am using a Windows-based platform (32-bit), installed with several programs from Singularity website and running on Git Bash attached with vagrant.

When I was trying to pull MitoZ file from Singularity hub, it failed. Hence, attached herewith the return command I received from Git Bash for your reference. Please kindly assist me with this matter.

**Comment by linzhi2013** [comment]
> ![error](https://user-images.githubusercontent.com/49437001/55791873-04c33c00-5af2-11e9-8ba4-73e40232a2cf.jpg)
> 
> I am using a Windows-based platform (32-bit), installed with several programs from Singularity website and running on Git Bash attached with vagrant.
> 
> When I was trying to pull MitoZ file from Singularity hub, it failed. Hence, attached herewith the return command I received from Git Bash for your reference. Please kindly assist me with this matter.

Hi!

Thank you for using MitoZ!

You should try to use the following command to pull the MitoZ singularity container (https://github.com/linzhi2013/MitoZ/blob/master/version_2.3/INSTALL.md):

`singularity pull  --name MitoZ.simg shub://linzhi2013/MitoZ:v2.3`

the command you used seems different from this command.

Meanwhile, I would like to address two concerns:
1. The singularity-hub is hosted on Google cloud, as far as I know. And Chinese users cannot access to google-related websites, and of course they cannot pull the singularity images from singularity-hub directly. That's why I wrote the following message in the INSTALL.md file:

>For China users, it can be difficult to pull the Singularity container from https://www.singularity-hub.org/ for known network problem, you can download the containers from https://pan.genomics.cn/ucdisk/s/uMFvum.

2. A typical Windows laptop/destop may not have enough computer resource for running mitogenome assembly with MitoZ, but `annotate`, `visualize` should be fine.

>It takes ~100G when we tested MitoZ with --thread_number 16. This is because MitoZ uses the de Bruijn graph (DBG) algorithm to perform de novo assembly. To learn more, see https://doi.org/10.1093/bioinformatics/btu077.

>there are ways to reduce the memory usage:

>enrich the mitochondrion during experiment step (e.g. via gene capture array). This can lead to a higher mitochondrial derived reads ratio in the HTS data, and then you can use less data for MitoZ input, which can reduce memory usage of MitoZ.

>filter out the mitochondrial reads by mapping reads against mitogenomes of closely-related species (if any). provide such reads (a smaller volume of data) to MitoZ.


Hope this helps.

Cheers,
Guanliang
