### ISSUE TITLE
Error running MitoZ on HPC: can not find taxid for ['Arthropoda'], maybe it's a misspelling.

### ISSUE THREAD

**Issue by mahsa-mousavi** [linzhi2013/MitoZ#73]
Hi, 

I've been trying to run MitoZ singularity container on HPC system. But using the below command (I used your test files), I get the following error message:
 `$ ./MitoZ_2.3.simg all --genetic_code 5 --clade Arthropoda --outprefix testContainer2.3 --thread_number 16 --fastq1 test.1.fq.gz --fastq2 test.2.fq.gz --fastq_read_length 150 --insert_size 250  --run_mode 2 --filter_taxa_method 1`

**error message:**
can not find taxid for Arthropoda
can not find taxid for ['Arthropoda'], maybe it's a misspelling.
Please use other taxanomy name  

I've already tested couple of things, but with no success:

1. I tested all other container versions on our HPC system. Version 1.0, 2.2 and 2.3 all give the same error message as above. But, if I only use the filter command, then it works fine and it generates the clean files. all2 command also fails with the same error message. 
 
Version 2.4alpha doesn't work at all, with similar error message as already reported in issue #36 (i.e.  /app/anaconda/bin/python3: can't open file '/app/release_MitoZ_v2.4-alpha/MitoZ.py': [Errno 2] No such file or directory) 

2. I pulled v2.3 container on a Cloud system with 60G of memory. It worked fine with your test data, but it failed on my real data (1.6G raw paired-end; generated 862M clean files, failed the assembly), with the error message `-K 71 -o work71 -s work71.soaptrans.lib -p 16`, which from other reported issues I can see it means memory is not enough.
  

From your source code I can see something is going wrong with ete3 (NCBITaxa.get_name_translator()), but I have no clue why it's only happening running MitoZ container on HPC. I highly appreciate if you could please give me some advice on how to fix the error.
Thank you.

Cheers,
Mahsa

**Comment by Prunoideae** [comment]
Hello Mahsa:
Have you already verified if your taxonomy database is valid?

Like:
```python
>>> from ete3 import NCBITaxa
>>> a = NCBITaxa()
>>> a.get_name_translator(["Arthropoda"])
{'Arthropoda': [6656]}
```

If this output nothing, then it's maybe there is something wrong with the database, and maybe redownloading the data and reload the local database can fix this.

This taxonomy search happens when it enters `findmitoscaf` stage, so it will be a problem for command `all`, `all2` and `findmitoscaf`, and other modules will work fine, since no taxonomy search is involved.

**Comment by mahsa-mousavi** [comment]
Thanks for your suggestions.
 
Unfortunately setting `--filter_taxa_method` option to 3 didn't solve the challenge and I'm still getting the very same error.

I can confirm that verifying taxonomy database via those commands failed and generated empty output. I am not sure if I understood your suggestion correctly, but I'll need to run MitoZ as singularity container on our HPC system as I don't have permission to install its source code or install ete3 to re-download the taxonomy database. Is there anything else that you could think of to get the container working? Any changes that I may be able to apply to its Dockerfile to make a new container?

Thanks very much in advance for your time.

Cheers,
Mahsa

**Comment by linzhi2013** [comment]
> I can confirm that verifying taxonomy database via those commands failed and generated empty output. I am not sure if I understood your suggestion correctly, but I'll need to run MitoZ as singularity container on our HPC system as I don't have permission to install its source code or install ete3 to re-download the taxonomy database. Is there anything else that you could think of to get the container working? Any changes that I may be able to apply to its Dockerfile to make a new container?

Dear Mahsa,

The Singularity version still needs to download and install the taxonomy database for package ete3 during your first runtime. This is due to the design of Singularity, which has no the `root` user in the container and thus can not package the taxonomy database for ete3 during the building of the Singularity container, instead, Singularity container has to mount the user's `HOME` into the container during each runtime. This means that during the first runtime, the Singularity version of MitoZ will install a taxonomy database in YOUR `HOME` directory.

Since the database is a bit large, and due to the design of ete3 package, it cannot be installed to somewhere else. If your `HOME` directory has not enough space, this can cause problems (e.g. leading to a broken database).

@Prunoideae 's idea is great. check for https://github.com/linzhi2013/MitoZ/blob/master/version_2.3/INSTALL.md.

First, shell into the Singularity container

    $ singularity shell /path/to/MitoZ.simg

In the container, run

    $ /app/anaconda/bin/python3


Then do something like this

```
>>> from ete3 import NCBITaxa
>>> a = NCBITaxa()
>>> a.get_name_translator(["Arthropoda"])
{'Arthropoda': [6656]}
```

If you get errors when running the above command, it suggests that the taxonomy database has something wrong. Then please read below.

1. check your `HOME` space.

    open another terminal, check if your `HOME` directory has >600M free space. If it does, go to step 2.

2. Remove the old database and reinstall a new one.

    In your Singularity container of MitoZ,

     $ rm -rf ~/.etetoolkit/    # to remove the old database

then, 

     $ /app/anaconda/bin/python3

which will bring you into the Python shell, now

```
from ete3 import NCBITaxa
ncbi = NCBITaxa()
ncbi.update_taxonomy_database()
```
It will automatically install the taxonomy database into `~/.etetoolkit/`. 

If your `HOME` directory has not enough space, please refer to https://github.com/linzhi2013/taxonomy_ranks/blob/master/README.md.

Finally, check if now MitoZ runs well.


And of course, you can install MitoZ from source (**3. Install from source code** https://github.com/linzhi2013/MitoZ/blob/master/version_2.3/INSTALL.md), unless your HPC cannot access to the Internet, which is needed when you install the dependencies and taxonomy database.


Cheers

**Comment by mahsa-mousavi** [comment]
Thank you very much. Yes, you were correct; there was not enough space in my HOME directory. Following explanation in links you provided I was able to fix it. 

It's working now :-) .  
Thanks a lot.

Cheers,
Mahsa

**Comment by linzhi2013** [comment]
> Thank you very much. Yes, you were correct; there was not enough space in my HOME directory. Following explanation in links you provided I was able to fix it.
> 
> It's working now :-) .
> Thanks a lot.
> 
> Cheers,
> Mahsa

Hi Mahsa,

I'm glad it helped you. Also thanks to @Prunoideae.

Cheers
