### ISSUE TITLE
changing MitoZ's  annotating database to annotate other type of mitogenome 

### ISSUE THREAD

**Issue by terserf** [linzhi2013/MitoZ#8]
Hi,
I've found MitoZ annotating mitogenome with a database of arthropods and mammals, if l want to annotate other type of mitogenome ,such as the molluscs, which means l need to change the database.  And  l want to know how to do that ?
thanks

**Comment by linzhi2013** [comment]
> Hi,
> I've found MitoZ annotating mitogenome with a database of arthropods and mammals, if l want to annotate other type of mitogenome ,such as the molluscs, which means l need to change the database. And l want to know how to do that ?
> thanks

Dear terserf,

Thanks for reporting the issue!
I am not quite sure what kind of clade that your interested species belong to, but I have actually built some HMM profiles for searching for mt-sequences and protein database for annotation for other clades in MitoZ. However,  since we still don’t have enough time and material to test their efficiency, I intendedly make them not available from the command lines currently.

Of course one can build his own HMM profiles for specific clades, but unfortunately I don’t have much time to document the detailed steps in a recent future. I am sorry for this.

If your interested species happens to be in the clades as below, the easiest way to work around is:

1.  Find the main script “MitoZ.py”

2. Then edit the “search_and_annot_mito_parser.add_argument” to be below (e.g. with a text editor like vi command, or Sublime Text, or notepad++, but never use Windows’s text editor):

```
search_and_annot_mito_parser.add_argument("--clade", default="Arthropoda",
        choices=["Chordata", "Arthropoda", "Echinodermata", "Annelida-segmented-worms", "Bryozoa", "Mollusca", "Nematoda", "Nemertea-ribbon-worms", "Porifera-sponges"],
        help="which clade does your species belong to? [%(default)s]")
```

Cheers,
Guanliang

**Comment by terserf** [comment]
Hi,
I've followed your advice that  by editing the “search_and_annot_mito_parser.add_argument” to make  MitoZ to annotate other type of mitogenome, it works really well !!!

However, I  think MitoZ  can do more , for example , I want to use MitoZ to assemble and annotate **virus’** mitogenome by adding the **virus’**  HMM profiles. But, I  do not  know how to do，about how to make a type of  **virus’**  HMM profiles，about which file I shoud edit?  Could you give me some advices，if use the "Suid herpesvirus 1" as example , whcih would be wonderful !
thanks

**Comment by linzhi2013** [comment]
> Hi,
> I've followed your advice that by editing the “search_and_annot_mito_parser.add_argument” to make MitoZ to annotate other type of mitogenome, it works really well !!!
> 
> However, I think MitoZ can do more , for example , I want to use MitoZ to assemble and annotate **virus’** mitogenome by adding the **virus’** HMM profiles. But, I do not know how to do，about how to make a type of **virus’** HMM profiles，about which file I shoud edit? Could you give me some advices，if use the "Suid herpesvirus 1" as example , whcih would be wonderful !
> thanks

Hi terserf,

As far as I know, virus does not have mitochondrial genome.

We have a pipeline for assembling the virus sequence from transcriptome data (please go to https://github.com/linzhi2013/Virusfishing), maybe this could help you?


If you would like to build HMM profiles for searching mitogenomes of a specific clade, you might:

1. get the same protein-coding genes (nucleotides) of different species of you interested clade
2. do multiple sequence alignment (MSA) for each gene, for example, with MAFFT.
3. build the HMM profile for each gene with HMMER (http://hmmer.org/).
4. place the built profiles to the directory where existing profiles are
5. do some changes to the “MitoZ.py” file as you did.

For the profiles of rRNA genes, build the profiles with http://eddylab.org/infernal/ after MSA.

Best

Guanliang

**Comment by linzhi2013** [comment]
Now it is documented at https://github.com/linzhi2013/MitoZ/wiki/Extending-MitoZ's-database
