### ISSUE TITLE
On the problem of annotated genes

### ISSUE THREAD

**Issue by zskysafe** [linzhi2013/MitoZ#83]
With the same data and the same settings, the assembly and annotation I made in February this year with mitoz is not the same as the result of assembly and annotation now.
In February, there were 37 genes, but now there are five PCGs missing.
The only difference is that the versions are different. In the annotated reference gene, the species I assembled have the same genus on NCBI.
Previous and current assembly results point to the same approximate species.
This is not a database or data problem, right?
I think it's the new version of mitoz that raises the threshold for identifying genes. Can we adjust this threshold?
![图片](https://user-images.githubusercontent.com/51896128/93016239-58448e00-f5f2-11ea-8794-64fea31e5880.png)

**Comment by linzhi2013** [comment]
Hi zskysfe,

Did the two sequences (left and right) in your screenshot both come from MitoZ? Because the sequence id in the left is not the id format generated by MitoZ. I suppose you modified the sequence ids by yourself.

version 2.4-alpha will forcibly extract part of input fastq data and use that this partial data for mitogenome assembly. This is because some new users often provide all the data they have directly to MitoZ, sometimes the data volume is quite large which makes MitoZ never finish running.

Different data can give different results, which makes sense. for example, smaller input fastq data can lead to incomplete mitogenomes, and many short contigs.

Therefore, the first step is to check if the left and right sequences are the same, with the help of Blast or/and MAFFT. Check their alignment.

Secondly, if the two sequences are exactly the same, then: 1. Did you change the annotation database? 2. may be a bug introduced in version 2.4-alpha.
