### ISSUE TITLE
cp: cannot stat 'visualization/circos.dep': No such file or directory

### ISSUE THREAD

**Issue by zskysafe** [linzhi2013/MitoZ#96]
[mitoz.log](https://github.com/linzhi2013/MitoZ/files/5740942/mitoz.log)

docker run -v $PWD:/project guanliangmeng/mitoz:2.4-alpha python3 /app/release_MitoZ_v2.4-alpha/MitoZ.py annotate --genetic_code 5 --clade Arthropoda \
--outprefix SPQA --thread_number 8 \
--fastafile ./SPQA.fas

**Comment by zskysafe** [comment]
Maybe there's a ‘_’ in it, so I changed it
>Scaphidium_quadrimaculatum ----  >SPQA


Although. Result is given, there are still errors
I don't know if it's my wrong way of running or where there is a problem
[mitoz.log](https://github.com/linzhi2013/MitoZ/files/5740987/mitoz.log)

**Comment by linzhi2013** [comment]
Maybe it was caused by this https://github.com/linzhi2013/MitoZ#46-fasta-file ？

>When you annotate a mitogenome sequence(s) stored in fasta file, the sequence id can not be too long, or MitoZ will fail. This is for some limitation in BioPython that MitoZ invokes.

**Comment by zskysafe** [comment]
When I use a short ID name, I still have this error. I tried it many times in docker

**Comment by linzhi2013** [comment]
Hello~

How short was your new sequence ID?

I just noticed this message in your provided log file:

`cp: cannot stat 'visualization/circos.dep': No such file or directory`

Maybe it's because that you didn't provide the fq files to calculate the aboundance along the mitogenome, and in MitoZ-2.4-alpha looked for this `visualization/circos.dep` file. If this is the case, MitoZ-2.3 will solve it.


Cheers
